### ISSUE TITLE
stream does not end when pipe?

### ISSUE THREAD

**Issue by genru** [Luuk-Dev/YT-Stream#12]
I am trying to upload a ytstream to S3, code looks like
```javascript
const video = await ytstream.stream(`https://www.youtube.com/watch?v=RCC1xZdFe_c`, {
        quality: 'low',
        type: 'audio',
        highWaterMark: 1048576 * 32,
        download: true
})
const passThrough = new PassThrough();
video.stream.pipe(passThrough);

// upload passThrough
const parallelUploads3 = new Upload({
        client: client,
        params: { Bucket: 'bucket', Key: key, Body: passThrough, ContentType: 'audio/mp3' },
        queueSize: 4, // optional concurrency configuration
        partSize: 1024 * 1024 * 30, // optional size of each part, in bytes, at least 5MB
       
 });
await parallelUploads3.done();    // <---- here programm stuck here
```

I tried to listen `end` event of ytstream, it not happen. is it good?

or do you have any advise of uploading stream to S3?

**Comment by Luuk-Dev** [comment]
Hey genru!

Sorry for my late response, I was quite busy the previous month. Personally I don't have any experience with the use of a `PassThrough` stream nor with uploading streams to S3 unfortunately. While running some tests, I did encounter a bug which caused the `finish` and `end` events of a `Writable` stream not to emit anymore, which I've just patched. Unfortunately this patch didn't emit the `finish` and `end` events of the `PassThrough` stream. Due to my lack of experience with `PassThrough` streams, I'm afraid I cannot help you further with this issue.

Kind regards,

Luuk
