### ISSUE TITLE
The YouTube song has no initial player response

### ISSUE THREAD

**Issue by drhuseyinunal** [Luuk-Dev/YT-Stream#6]
i have this error: 'The YouTube song has no initial player response'

i'm using the code:

(async () => {
			stream = await ytstream.stream(`https://www.youtube.com/watch?v=dQw4w9WgXcQ`, {
				quality: 'high',
				type: 'audio',
				highWaterMark: 1048576 * 32,
			});
			stream.stream.pipe(fs.createWriteStream('some_song.mp3'));
			console.log(stream.video_url);
			console.log(stream.url);
		})();
		return;

**Comment by Luuk-Dev** [comment]
I've tried to recreate this error but was unable to with the code you've given. In addition, I went to the YouTube page and was able to find the initial player response in the source code of the page. The error is not caused by the code but gets caused by making the request. Possible reasons why you aren't able to make the request are:
* A firewall blocks you from making the request to the YouTube page
* The ip was banned from YouTube which doesn't allow you to view the video
* You are not allowed to view the video from the country where your server/pc is located
Please check if you are able to view the video from the client-side with the same ip and can find an initial player response in the source code of the page.

**Comment by drhuseyinunal** [comment]
i have an 429 error with another npm module. I installed your module because of that. How can i fix the error?

**Comment by Luuk-Dev** [comment]
A 429 error is caused due too many requests to a page, so you're basically rate-limited. This mostly gets caused because of others making requests to YouTube on the same IP. You can either use another server with a different IP to make the request or bypass the rate-limit with a Proxy. The last option has a higher chance of getting rate-limited again.

**Comment by drhuseyinunal** [comment]
is your package support for bypassing rate-limit with Proxy? if it is, could you help me about it? 
And... Could you tell me, what is the request rate-limit per second?

**Comment by Luuk-Dev** [comment]
The YT-Stream package doesn't support proxy's, the [ytdl-core](https://github.com/fent/node-ytdl-core/blob/master/example/proxy.js) does though, but requires you having access to a server with a password. There is notwhere mentioned by YouTube what the limit is per second. I've been told that the chance of a rate-limit also is lower when you use a cookie, but I'm not sure if this is true.

**Comment by drhuseyinunal** [comment]
okay, thank you so much
